e2e tests done
BME-MIT-IET/iet-hf-2023-ajandekutalvany pull request #11
Opened 2023-05-29 09:37 UTC by notAnElephant

using Cypress

2023-05-29 09:41 UTC, KostyalBalint requested changes
Pleas remove the node_modules folder, and add it .gitignore

2023-05-29 12:41 UTC, Taurusz1 commented
Removed node_modules, and added it to .gitignore.

2023-05-29 17:47 UTC, KostyalBalint approved these changes
lgtm

2023-06-01 07:30 UTC, KostyalBalint approved these changes

2023-06-02 08:36 UTC, merged